### ISSUE TITLE
The ability to control NPU/Hexagon DSP clock and voltage?

### ISSUE THREAD

**Issue by BlackSoulxxx** [libxzr/KonaBess#11]
Hi, it is possible to control the NPU/Hexagon DSP clock and voltage from the kernel? It seems to me they also using the same voltage stepping mechanism as Adreno GPU, hence the possibility of undervolt/overclock this part of the SoC. I hope it would be easy to do like the Adreno GPU one.
NPU voltage table for example:
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/haydn-r-oss/include/linux/soc/qcom/cdsprm_cxlimit.h

**Comment by amaterasushen** [comment]
great question.

**Comment by libxzr** [comment]
I don't think NPU / DSP undervolt is something critical that can easily test and feel.

**Whatever, contribution is welcome.**
