### ISSUE TITLE
Xiaomi kona devices cannot go above 905MHz clock?

### ISSUE THREAD

**Issue by BlackSoulxxx** [libxzr/KonaBess#12]
I discovered on my K30 Pro Zoom (lmipro) this weird issue that you cannot go above 905MHz, even with extra voltage/overvolt. The device simply will go unstable and crashes. Tested with various MIUI, from MIUI 12.0 to latest China beta, same weird issue. I tried on my friends K30 Pro (lmi) and it behave the same. On 900MHz clock the device is stable and can even undervolt some more. But on other brands kona devices, it can go up more than 1GHz. Is this issue only happens with Xiaomi and why this happens? Can Konabess workaround this issue? Thank you.

**Comment by libxzr** [comment]
This mainly depends on your chip quality imo.
