### ISSUE TITLE
sd690 - enable new frequency fail

### ISSUE THREAD

**Issue by Aarqw12** [libxzr/KonaBess#13]
*stock gpu frequency in my phone is max 565mhz .

 I see voltage table support too 650,800,850 in stock dtb.

If we enable 650mhz and reboot phone , going to this frequency will create blank screen and panic. sd690 really support edit ?

**Comment by libxzr** [comment]
Thats quite normal.
Not all chips are able to be overclocked without limits.
(Someone explained qualcomm locked it in tz)

Here's the max frequency some chips can reach that I know of
- sd865 unlimited
- sd855 unlimited
- sd888 ~855mhz
- sd870 683mhz or unlimited
- sd865plus 670mhz
- sd765g ~635mhz
