### ISSUE TITLE
Snapdragon 870

### ISSUE THREAD

**Issue by Rstment25** [libxzr/KonaBess#15]
Hello , I'm curious how can we know if Snapdragon 870 that we have is locked or not?

I'm not able to get my phone ( poco f3 ) in Kona past 683mhz ... When I asked others that are able to overclock theirs they told me I need to delete frequency table entirely and then the chip will lock at highest freq.
( I already have peltier cooler so I'd like to give this a shot but idk how ... Through Kona I'm not able to delete frequency table . When I asked further I got 2 advices : frequency table is inside boot partition and the other advice from different person was I need to delete it from kernel ? ) 

Now which one it is ? Could you point me in the right direction? I'd love to be able to do this through Kona if it is possible to delete frequency table entirety from boot partition? Idk ... When I try flashing with every frequency deleted I get error from Kona. ( I can attach the error if you want ? It's probably complaining that there's nothing inside frequency table ... )

If you don't have this phone but would like to experiment on mine I'm here ... Feel free to reach out

Ty!

**Comment by libxzr** [comment]
imo whether it can be overclocked depends only on the factory batch. Some people have concluded that if your factory data is later than 20/3/2021, then you are mostly not able to overclock to higher than 683mhz. I don't think this is can be workaround by somehow removing the frequency table.

**Comment by libxzr** [comment]
imo whether it can be overclocked depends only on the factory batch. Some people have concluded that if your factory data is later than 20/3/2021, then you are mostly not able to overclock to higher than 683mhz. I don't think this is can be workaround by somehow removing the frequency table.

**Comment by Rstment25** [comment]
Can you leave some tips on how one would go about removing frequency table tho?

I'd like to at least give this a try before I sell this phone, who knows it might be possible

**Comment by libxzr** [comment]
> Can you leave some tips on how one would go about removing frequency table tho?
> 
> I'd like to at least give this a try before I sell this phone, who knows it might be possible
> 
> @libxzr

Build your own kernel dtb from source, remove frequency tables and all references from it. But konabess is not designed to do this so you have to do this manually.

**Comment by Rstment25** [comment]
Ty !

One question though... Building dtb from source doesn't seem like it will be possible on pretty much any device but Google pixels ( They provide dtb source as well )

How do you go around this ?

I see that Kona decompiles dtb then recompiles and flashes the changes. ( I got it that it's not possible to do through Kona don't worry ) Can the same be done by manually decompiling or is this only possible because you tested on a different phone with dtb sources available so you figured out which files are necessary and where they are located beforehand?

**Comment by libxzr** [comment]
> Ty !
> 
> One question though... Building dtb from source doesn't seem like it will be possible on pretty much any device but Google pixels ( They provide dtb source as well )
> 
> How do you go around this ?
> 
> I see that Kona decompiles dtb then recompiles and flashes the changes. ( I got it that it's not possible to do through Kona don't worry ) Can the same be done by manually decompiling or is this only possible because you tested on a different phone with dtb sources available so you figured out which files are necessary and where they are located beforehand?
> 
> @libxzr

You can take use of konabess's decompiling and repacking logic.
Open konabess and then open `/data/data/xzr.konabess/files` using any root file explorer. You will find decompiled dtb files there like `0.dts 1.dts 2.dts`. Do what you want to them and back to konabess, press `repack and flash new image` and all the changes you done will be applied to your boot image.

**Comment by Rstment25** [comment]
I'm off to bed now but when I wake up I'll try doing this.

Many thanks!
