### ISSUE TITLE
SD 855 - Custom or Stock Kernel? 

### ISSUE THREAD

**Issue by varunpilankar** [libxzr/KonaBess#17]
Hi Dev.

Will this work with custom or Stock Kernel?

I'm currently running a custom - ex kernel on A10.

I have installed your app but can't see CPU voltage table at all.

**Comment by ianchb** [comment]
The fact is: I am not using the custom kernel but still no voltge table at all.
(780G,renoir)

**Comment by varunpilankar** [comment]
> The fact is: I am not using the custom kernel but still no voltge table at all.
> (780G,renoir)

That's what I guess.. Coz the dev mentioned undervolting CPU but I couldn't see any on my device as well.

**Comment by libxzr** [comment]
You can never undervolt cpu with this. This only works for gpu.
