### ISSUE TITLE
If the GPU lines are in boot.img, the CPU lines too?

### ISSUE THREAD

**Issue by vinyimp** [libxzr/KonaBess#20]
First of all I want to thank the _**LIBXZR**_, recognition and respect always in the first place!

Well, I have a OnePlus 9R - SNAP 870 _**(almost a fireball)**_ and I got a 50% improvement following the footsteps of _**Patrick Morgan**_ (XDA - RedMagic 5G/5S) and _**Dr.Brown**_ (YouTuber). 

A little underclock and some undervolt made my device a little colder but it's not perfect and I say why _**(this is a suggestion, I don't know the possibility of it but it makes sense).**_

The CPU also needs undervolt, just like desktop/laptop processors - maybe not as aggressive _**(something safe, between -25mv to -100mv)**_ without increasing clocks. 

The CPU is involved in the main tasks of the device and consequently also in the games, the GPU does not heat itself and because they are not separated, any heating _**(whoever it is)**_ inflicts on the other's performance, stability and temperature.

On the 800 line processors _**(SNAPDRAGON)**_ for me they don't need overclocking, everyone has plenty of power _**(nothing against those who want to do it)**_, what's missing is greater control over temperature. 

So _**LIBXZR**_, if the voltage lines from the GPU are in boot.img _**(which I believe is the KERNEL)**_ are those from the CPU too? I would like you to reconsider this, I'm not doing ETA or anything, I just have compliments on your project and purpose, this is all a plausible suggestion.

If you need testers, I apply now!
- @neryimp _**(Telegram)**_

Success!

**Comment by libxzr** [comment]
No, cpu tables are not in boot.img.
https://github.com/libxzr/KonaBess/issues/7

**Comment by vinyimp** [comment]
> No, cpu tables are not in boot.img. #7

Ah, sad but I understand perfectly!

I talked to the people I quoted in the post and they told me that timing and volts is locked by Qualcomm

That such changes would not be possible, despite being in the same SOC _**(CPU and GPU)**_ they are different sectors and may be locked :(

Thanks for the reply, I will continue to follow your work!
